; mfma_f16_16x16x16.s
;
; Target concept: CDNA-class AMDGPU, one 64-lane wavefront.
; Computes a single C[16,16] += A[16,16] * B[16,16] tile.
;
; ABI assumptions:
; s[0:1] = A base pointer, FP16 row-major
; s[2:3] = B base pointer, FP16 row-major
; s[4:5] = C base pointer, FP32 row-major
;
; IMPORTANT:
; Exact VGPR fragment mapping and legal operand tuple widths are
; ISA- and GPU-generation-specific. Verify against llvm-mc and AMD's
; ISA manual for your --mcpu target.

        .text
        .amdgcn_target "amdgcn-amd-amdhsa--gfx90a"
        .p2align 8
        .globl mfma_f16_16x16x16
        .type mfma_f16_16x16x16,@function

mfma_f16_16x16x16:
        ; Each lane gets its wavefront-local ID.
        v_mbcnt_lo_u32_b32 v0, -1, 0
        v_mbcnt_hi_u32_b32 v0, -1, v0

        ; -----------------------------------------------------------
        ; Fragment loads.
        ;
        ; Real MFMA code needs the exact lane -> A/B element mapping
        ; defined by v_mfma_f32_16x16x16f16. Usually you construct
        ; lane-dependent byte addresses, load packed FP16, then use
        ; the proper low/high-half operands.
        ; -----------------------------------------------------------

        ; Example lane-relative byte offsets, schematic only:
        v_lshlrev_b32 v1, 1, v0 ; 2-byte FP16 offset
        v_add_co_u32 v2, vcc, s0, v1
        v_addc_co_u32 v3, vcc, s1, 0, vcc
        global_load_ushort v4, v[2:3], off

        v_add_co_u32 v5, vcc, s2, v1
        v_addc_co_u32 v6, vcc, s3, 0, vcc
        global_load_ushort v7, v[5:6], off

        s_waitcnt vmcnt(0)

        ; -----------------------------------------------------------
        ; Accumulator initialization.
        ;
        ; A 16x16 FP32 output tile is distributed across wave lanes.
        ; The actual destination/accumulator tuple requirement is
        ; target-specific. This shows four FP32 accumulator registers
        ; per lane as a representative CDNA-style fragment.
        ; -----------------------------------------------------------

        v_mov_b32 v8, 0
        v_mov_b32 v9, 0
        v_mov_b32 v10, 0
        v_mov_b32 v11, 0

        ; -----------------------------------------------------------
        ; D = A * B + C
        ;
        ; Conceptual MFMA form:
        ; v_mfma_f32_16x16x16f16 D, A, B, C, cbsz, abid, blgp
        ;
        ; `v4` and `v7` must contain correctly packed/placed source
        ; fragments. v[8:11] represents C and receives D here.
        ; -----------------------------------------------------------

        v_mfma_f32_16x16x16f16 v[8:11], v4, v7, v[8:11], 0, 0, 0

        ; -----------------------------------------------------------
        ; Store result fragment.
        ;
        ; This requires the inverse lane -> C[16,16] mapping. The
        ; simple consecutive stores below are schematic: use the
        ; mapping generated by amd_matrix_instruction_calculator or
        ; an equivalent verified table for a real kernel.
        ; -----------------------------------------------------------

        v_lshlrev_b32 v12, 2, v0 ; 4-byte FP32 lane offset
        v_add_co_u32 v13, vcc, s4, v12
        v_addc_co_u32 v14, vcc, s5, 0, vcc
        global_store_dword v[13:14], v8, off

        s_endpgm